# Generated by Django 5.0.6 on 2024-06-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='fact',
            field=models.CharField(max_length=150),
        ),
    ]
